run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - errcheck
    - unused
    - protogetter
    - gci
    - goconst
    - dupl

linters-settings:
  protogetter:
    check-generated: false 

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _gen/|pb/|proto/
      linters:
        - gofmt
        - goimports
