services:
  postgres:
    image: postgres:15
    container_name: student_db
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: studentdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d studentdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  student-service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: student
      DB_PASS: 111111
      CONFIG_PATH: /app/config.yaml
    ports:
      - "50051:50051"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped

volumes:
  pgdata:
