// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: student.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for student status
type Student_Status int32

const (
	Student_STATUS_UNSPECIFIED Student_Status = 0
	Student_ACTIVE             Student_Status = 1
	Student_GRADUATED          Student_Status = 2
	Student_SUSPENDED          Student_Status = 3
	Student_EXCHANGE           Student_Status = 4
)

// Enum value maps for Student_Status.
var (
	Student_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "GRADUATED",
		3: "SUSPENDED",
		4: "EXCHANGE",
	}
	Student_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ACTIVE":             1,
		"GRADUATED":          2,
		"SUSPENDED":          3,
		"EXCHANGE":           4,
	}
)

func (x Student_Status) Enum() *Student_Status {
	p := new(Student_Status)
	*p = x
	return p
}

func (x Student_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Student_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_student_proto_enumTypes[0].Descriptor()
}

func (Student_Status) Type() protoreflect.EnumType {
	return &file_student_proto_enumTypes[0]
}

func (x Student_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Student_Status.Descriptor instead.
func (Student_Status) EnumDescriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{0, 0}
}

type Student struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Grade     int32                  `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// unset = unknown, zero value = no middle name
	MiddleName  *string          `protobuf:"bytes,6,opt,name=middle_name,json=middleName,proto3,oneof" json:"middle_name,omitempty"`
	Status      Student_Status   `protobuf:"varint,7,opt,name=status,proto3,enum=student.Student_Status" json:"status,omitempty"`
	HomeAddress *Student_Address `protobuf:"bytes,8,opt,name=home_address,json=homeAddress,proto3" json:"home_address,omitempty"`
	// Types that are valid to be assigned to StudentDetails:
	//
	//	*Student_Local
	//	*Student_Exchange
	StudentDetails isStudent_StudentDetails `protobuf_oneof:"student_details"`
	Friends        []string                 `protobuf:"bytes,11,rep,name=friends,proto3" json:"friends,omitempty"`
	CourseGrades   map[string]string        `protobuf:"bytes,12,rep,name=course_grades,json=courseGrades,proto3" json:"course_grades,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Student) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Student) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Student) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Student) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Student) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *Student) GetStatus() Student_Status {
	if x != nil {
		return x.Status
	}
	return Student_STATUS_UNSPECIFIED
}

func (x *Student) GetHomeAddress() *Student_Address {
	if x != nil {
		return x.HomeAddress
	}
	return nil
}

func (x *Student) GetStudentDetails() isStudent_StudentDetails {
	if x != nil {
		return x.StudentDetails
	}
	return nil
}

func (x *Student) GetLocal() *Student_LocalStudent {
	if x != nil {
		if x, ok := x.StudentDetails.(*Student_Local); ok {
			return x.Local
		}
	}
	return nil
}

func (x *Student) GetExchange() *Student_ExchangeStudent {
	if x != nil {
		if x, ok := x.StudentDetails.(*Student_Exchange); ok {
			return x.Exchange
		}
	}
	return nil
}

func (x *Student) GetFriends() []string {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *Student) GetCourseGrades() map[string]string {
	if x != nil {
		return x.CourseGrades
	}
	return nil
}

type isStudent_StudentDetails interface {
	isStudent_StudentDetails()
}

type Student_Local struct {
	Local *Student_LocalStudent `protobuf:"bytes,9,opt,name=local,proto3,oneof"`
}

type Student_Exchange struct {
	Exchange *Student_ExchangeStudent `protobuf:"bytes,10,opt,name=exchange,proto3,oneof"`
}

func (*Student_Local) isStudent_StudentDetails() {}

func (*Student_Exchange) isStudent_StudentDetails() {}

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStudentRequest) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

type CreateStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentResponse) Reset() {
	*x = CreateStudentResponse{}
	mi := &file_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentResponse) ProtoMessage() {}

func (x *CreateStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentResponse.ProtoReflect.Descriptor instead.
func (*CreateStudentResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentResponse) Reset() {
	*x = GetStudentResponse{}
	mi := &file_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentResponse) ProtoMessage() {}

func (x *GetStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentResponse.ProtoReflect.Descriptor instead.
func (*GetStudentResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

type UpdateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentRequest) Reset() {
	*x = UpdateStudentRequest{}
	mi := &file_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentRequest) ProtoMessage() {}

func (x *UpdateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStudentRequest) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

type DeleteStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentRequest) Reset() {
	*x = DeleteStudentRequest{}
	mi := &file_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentRequest) ProtoMessage() {}

func (x *DeleteStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStudentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         int32                  `protobuf:"varint,1,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsRequest) Reset() {
	*x = ListStudentsRequest{}
	mi := &file_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsRequest) ProtoMessage() {}

func (x *ListStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsRequest.ProtoReflect.Descriptor instead.
func (*ListStudentsRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{7}
}

func (x *ListStudentsRequest) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

type ListStudentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsResponse) Reset() {
	*x = ListStudentsResponse{}
	mi := &file_student_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsResponse) ProtoMessage() {}

func (x *ListStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsResponse.ProtoReflect.Descriptor instead.
func (*ListStudentsResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{8}
}

func (x *ListStudentsResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type Student_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student_Address) Reset() {
	*x = Student_Address{}
	mi := &file_student_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student_Address) ProtoMessage() {}

func (x *Student_Address) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student_Address.ProtoReflect.Descriptor instead.
func (*Student_Address) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Student_Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Student_Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Student_Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type Student_LocalStudent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NationalId    string                 `protobuf:"bytes,1,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	Scholarship   bool                   `protobuf:"varint,2,opt,name=scholarship,proto3" json:"scholarship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student_LocalStudent) Reset() {
	*x = Student_LocalStudent{}
	mi := &file_student_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student_LocalStudent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student_LocalStudent) ProtoMessage() {}

func (x *Student_LocalStudent) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student_LocalStudent.ProtoReflect.Descriptor instead.
func (*Student_LocalStudent) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Student_LocalStudent) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

func (x *Student_LocalStudent) GetScholarship() bool {
	if x != nil {
		return x.Scholarship
	}
	return false
}

type Student_ExchangeStudent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HomeUniversity  string                 `protobuf:"bytes,1,opt,name=home_university,json=homeUniversity,proto3" json:"home_university,omitempty"`
	CountryOfOrigin string                 `protobuf:"bytes,2,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	ProgramStart    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=program_start,json=programStart,proto3" json:"program_start,omitempty"`
	ProgramEnd      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=program_end,json=programEnd,proto3" json:"program_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Student_ExchangeStudent) Reset() {
	*x = Student_ExchangeStudent{}
	mi := &file_student_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student_ExchangeStudent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student_ExchangeStudent) ProtoMessage() {}

func (x *Student_ExchangeStudent) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student_ExchangeStudent.ProtoReflect.Descriptor instead.
func (*Student_ExchangeStudent) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Student_ExchangeStudent) GetHomeUniversity() string {
	if x != nil {
		return x.HomeUniversity
	}
	return ""
}

func (x *Student_ExchangeStudent) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *Student_ExchangeStudent) GetProgramStart() *timestamppb.Timestamp {
	if x != nil {
		return x.ProgramStart
	}
	return nil
}

func (x *Student_ExchangeStudent) GetProgramEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.ProgramEnd
	}
	return nil
}

var File_student_proto protoreflect.FileDescriptor

const file_student_proto_rawDesc = "" +
	"\n" +
	"\rstudent.proto\x12\astudent\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\b\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05grade\x18\x04 \x01(\x05R\x05grade\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12$\n" +
	"\vmiddle_name\x18\x06 \x01(\tH\x01R\n" +
	"middleName\x88\x01\x01\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.student.Student.StatusR\x06status\x12;\n" +
	"\fhome_address\x18\b \x01(\v2\x18.student.Student.AddressR\vhomeAddress\x125\n" +
	"\x05local\x18\t \x01(\v2\x1d.student.Student.LocalStudentH\x00R\x05local\x12>\n" +
	"\bexchange\x18\n" +
	" \x01(\v2 .student.Student.ExchangeStudentH\x00R\bexchange\x12\x18\n" +
	"\afriends\x18\v \x03(\tR\afriends\x12G\n" +
	"\rcourse_grades\x18\f \x03(\v2\".student.Student.CourseGradesEntryR\fcourseGrades\x1aO\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x1aQ\n" +
	"\fLocalStudent\x12\x1f\n" +
	"\vnational_id\x18\x01 \x01(\tR\n" +
	"nationalId\x12 \n" +
	"\vscholarship\x18\x02 \x01(\bR\vscholarship\x1a\xe4\x01\n" +
	"\x0fExchangeStudent\x12'\n" +
	"\x0fhome_university\x18\x01 \x01(\tR\x0ehomeUniversity\x12*\n" +
	"\x11country_of_origin\x18\x02 \x01(\tR\x0fcountryOfOrigin\x12?\n" +
	"\rprogram_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fprogramStart\x12;\n" +
	"\vprogram_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"programEnd\x1a?\n" +
	"\x11CourseGradesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tGRADUATED\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x03\x12\f\n" +
	"\bEXCHANGE\x10\x04B\x11\n" +
	"\x0fstudent_detailsB\x0e\n" +
	"\f_middle_name\"B\n" +
	"\x14CreateStudentRequest\x12*\n" +
	"\astudent\x18\x01 \x01(\v2\x10.student.StudentR\astudent\"'\n" +
	"\x15CreateStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetStudentResponse\x12*\n" +
	"\astudent\x18\x01 \x01(\v2\x10.student.StudentR\astudent\"B\n" +
	"\x14UpdateStudentRequest\x12*\n" +
	"\astudent\x18\x01 \x01(\v2\x10.student.StudentR\astudent\"&\n" +
	"\x14DeleteStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x13ListStudentsRequest\x12\x14\n" +
	"\x05grade\x18\x01 \x01(\x05R\x05grade\"D\n" +
	"\x14ListStudentsResponse\x12,\n" +
	"\bstudents\x18\x01 \x03(\v2\x10.student.StudentR\bstudents2\x84\x03\n" +
	"\x0eStudentService\x12N\n" +
	"\rCreateStudent\x12\x1d.student.CreateStudentRequest\x1a\x1e.student.CreateStudentResponse\x12E\n" +
	"\n" +
	"GetStudent\x12\x1a.student.GetStudentRequest\x1a\x1b.student.GetStudentResponse\x12F\n" +
	"\rUpdateStudent\x12\x1d.student.UpdateStudentRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rDeleteStudent\x12\x1d.student.DeleteStudentRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\fListStudents\x12\x1c.student.ListStudentsRequest\x1a\x1d.student.ListStudentsResponseB)Z'example.com/student-service/proto;protob\x06proto3"

var (
	file_student_proto_rawDescOnce sync.Once
	file_student_proto_rawDescData []byte
)

func file_student_proto_rawDescGZIP() []byte {
	file_student_proto_rawDescOnce.Do(func() {
		file_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_proto_rawDesc), len(file_student_proto_rawDesc)))
	})
	return file_student_proto_rawDescData
}

var file_student_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_student_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_student_proto_goTypes = []any{
	(Student_Status)(0),             // 0: student.Student.Status
	(*Student)(nil),                 // 1: student.Student
	(*CreateStudentRequest)(nil),    // 2: student.CreateStudentRequest
	(*CreateStudentResponse)(nil),   // 3: student.CreateStudentResponse
	(*GetStudentRequest)(nil),       // 4: student.GetStudentRequest
	(*GetStudentResponse)(nil),      // 5: student.GetStudentResponse
	(*UpdateStudentRequest)(nil),    // 6: student.UpdateStudentRequest
	(*DeleteStudentRequest)(nil),    // 7: student.DeleteStudentRequest
	(*ListStudentsRequest)(nil),     // 8: student.ListStudentsRequest
	(*ListStudentsResponse)(nil),    // 9: student.ListStudentsResponse
	(*Student_Address)(nil),         // 10: student.Student.Address
	(*Student_LocalStudent)(nil),    // 11: student.Student.LocalStudent
	(*Student_ExchangeStudent)(nil), // 12: student.Student.ExchangeStudent
	nil,                             // 13: student.Student.CourseGradesEntry
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 15: google.protobuf.Empty
}
var file_student_proto_depIdxs = []int32{
	14, // 0: student.Student.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: student.Student.status:type_name -> student.Student.Status
	10, // 2: student.Student.home_address:type_name -> student.Student.Address
	11, // 3: student.Student.local:type_name -> student.Student.LocalStudent
	12, // 4: student.Student.exchange:type_name -> student.Student.ExchangeStudent
	13, // 5: student.Student.course_grades:type_name -> student.Student.CourseGradesEntry
	1,  // 6: student.CreateStudentRequest.student:type_name -> student.Student
	1,  // 7: student.GetStudentResponse.student:type_name -> student.Student
	1,  // 8: student.UpdateStudentRequest.student:type_name -> student.Student
	1,  // 9: student.ListStudentsResponse.students:type_name -> student.Student
	14, // 10: student.Student.ExchangeStudent.program_start:type_name -> google.protobuf.Timestamp
	14, // 11: student.Student.ExchangeStudent.program_end:type_name -> google.protobuf.Timestamp
	2,  // 12: student.StudentService.CreateStudent:input_type -> student.CreateStudentRequest
	4,  // 13: student.StudentService.GetStudent:input_type -> student.GetStudentRequest
	6,  // 14: student.StudentService.UpdateStudent:input_type -> student.UpdateStudentRequest
	7,  // 15: student.StudentService.DeleteStudent:input_type -> student.DeleteStudentRequest
	8,  // 16: student.StudentService.ListStudents:input_type -> student.ListStudentsRequest
	3,  // 17: student.StudentService.CreateStudent:output_type -> student.CreateStudentResponse
	5,  // 18: student.StudentService.GetStudent:output_type -> student.GetStudentResponse
	15, // 19: student.StudentService.UpdateStudent:output_type -> google.protobuf.Empty
	15, // 20: student.StudentService.DeleteStudent:output_type -> google.protobuf.Empty
	9,  // 21: student.StudentService.ListStudents:output_type -> student.ListStudentsResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_student_proto_init() }
func file_student_proto_init() {
	if File_student_proto != nil {
		return
	}
	file_student_proto_msgTypes[0].OneofWrappers = []any{
		(*Student_Local)(nil),
		(*Student_Exchange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_proto_rawDesc), len(file_student_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_student_proto_goTypes,
		DependencyIndexes: file_student_proto_depIdxs,
		EnumInfos:         file_student_proto_enumTypes,
		MessageInfos:      file_student_proto_msgTypes,
	}.Build()
	File_student_proto = out.File
	file_student_proto_goTypes = nil
	file_student_proto_depIdxs = nil
}
